[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Критические флаги для хака raw packets
build_flags = 
    -Wl,-z,muldefs
    -DCONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE=0
    -DARDUINO_ARCH_ESP32

; Указываем пути к заголовкам, если они лежат нестандартно
build_src_filter = +<*> -<.git/> -<.svn/>

lib_deps = 
    ; Если патч требует конкретных версий библиотек, укажи их здесь
