[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Флаги сборки
build_flags = 
    -Wl,-z,muldefs ; Разрешает множественные определения (нужно для хака sanity_check)
    -DCONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE=0

; Подключение библиотек
lib_deps = 
    ; Здесь можно добавить библиотеки, если нужны, но стандартных WiFi.h достаточно

; Важно: Для работы raw packets на C3 может потребоваться кастомное ядро.
; Если этот код не работает, попробуй использовать platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
; Или примени патч вручную, заменив файлы в папке платформы.
